---
# tasks file for dynatrace

- name: Check if Dynatrace OneAgent is already present
  stat:
    path: /opt/dynatrace/oneagent/agent/lib64/liboneagentos.so
  register: dynatrace_agent_installed
  tags: configure

- name: Download and install Dynatrace OneAgent
  block:
    - name: Download Dynatrace OneAgent
      get_url:
        url: "{{ dynatrace_oneagent_installer_script_url }}"
        dest: "/tmp/dynatrace-oneagent.sh"
      no_log: true

    - name: Install Dynatrace OneAgent
      shell: "sh /tmp/dynatrace-oneagent.sh APP_LOG_CONTENT_ACCESS={{ dynatrace_app_log_content_access }} HOST_GROUP={{ dynatrace_host_group }}"
      become: true
      tags:
        - skip_ansible_lint

  when:
    - not dynatrace_agent_installed.stat.exists
    - dynatrace_oneagent_installer_script_url is not none
    - dynatrace_install_oneagent | bool
  tags: configure
