
- name: Install redis
  apt:
    pkg: "redis-server"
    state: present
  tags:
  - packages
  - redis

- name: Configure redis
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "^bind "
    state: "absent"
  register: configure_redis
  notify: Restart redis
  tags:
  - redis


- name: Ensure redis is started
  service:
    name: redis-server
    state: started
  tags:
  - redis
