---

- name: Ensure namespace path is present
  file:
    path: "/var/www/ns"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy namespace documentation
  synchronize:
    src: "files/index.html"
    dest: "/var/www/ns"

- name: Copy namespace documentation
  synchronize:
    src: "{{ item }}"
    dest: "/var/www/ns"
  with_items:
    - files/index.html
    - files/avoindata_dcat-ap_shacl.ttl
    - files/FOAF.ttl
