---

- name: Restart Apache
  service: name=apache2 state=restarted

- name: Restart supervisor services
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_flattened:
    - "{{ ckan_supervisor_services }}"
