---

- name: Restart CKAN
  shell: supervisorctl restart 'ckan:'

- name: Restart supervisor services
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_flattened:
    - "{{ ckan_supervisor_services }}"
