AWSTemplateFormatVersion: "2010-09-09"
Description: opendata clamav ecr

Resources:
  ClamAvRepository:
    Type: AWS::ECR::Repository
    Properties: 
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Only keep 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }
      RepositoryName: clamav-scanner

Outputs:
  EcrRepositoryArn:
    Description: ECR repository ARN
    Value: !GetAtt ClamAvRepository.Arn
    Export:
      Name: avoindata-clamav-ecr-arn
