---

- name: User creation
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups | join(',') }}"
    state: "{{ item.state }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
  with_items: "{{ common_users }}"
  no_log: true

- name: Add public keys
  authorized_key:
    exclusive: yes
    key: "{{ item.publickeys | join('\n') }}"
    user: "{{ item.username }}"
  with_items: "{{ common_users }}"
  when: item.state == "present"
  no_log: true

- name: Copy sudoers file for editing
  copy:
    remote_src: true
    src: "/etc/sudoers"
    dest: "/etc/sudoers.tmp"
  no_log: true

- name: Ensure passwordless sudo for sudo group
  lineinfile:
    dest: "/etc/sudoers.tmp"
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
  register: sudoers_wheel_conf
  no_log: true

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  when: sudoers_wheel_conf.changed |bool
  no_log: true
  tags:
    - skip_ansible_lint
