---
# tasks file for common
- name: Check submodule status
  delegate_to: localhost
  become: false
  shell: >
    git submodule status --recursive| egrep '^[+-]' -c
  args:
    chdir: "{{ playbook_dir }}"
  register: common_submodule_status
  failed_when: common_submodule_status.rc > 1
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Pause if currently checked out submodule commit does not match repo
  delegate_to: localhost
  become: false
  pause:
    prompt: "{{ common_submodule_status.stdout }} modules have changed, continue?"
  when:
    - common_submodule_status.stdout > "0"
    - not common_skip_submodule_check

- name: Copy apt sources.list
  template:
    src: "sources.list.j2"
    dest: "/etc/apt/sources.list"
    mode: "0644"
    owner: root
    group: root
    backup: true
  when: common_deployment_environment_id == "vagrant"

- name: Update apt cache
  apt:
    update_cache: yes

# Dist-upgrade is disabled in vagrant as it breaks virtualbox guest additions
- name: Update packages
  apt:
    upgrade: "{{ common_apt_upgrade }}"
  when: common_deployment_environment_id != "vagrant"

- name: Set locale
  lineinfile:
    path: "/etc/environment"
    line: "LC_ALL=en_US.utf8"
    regexp: "^LC_ALL=.*"


# Swap file configuration

- name: Enable zswap (insert)
  lineinfile:
    path: '{{ zswap_grubfile }}'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?!.*?zswap\.enabled=[01]).*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 zswap.enabled=1"'
    backrefs: yes
  notify:
    - update-grub

- name: Enable zswap (update)
  lineinfile:
    path: '{{ zswap_grubfile }}'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*?)zswap\.enabled=[01](.*?)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1zswap.enabled=1\2"'
    backrefs: yes
  notify:
    - update-grub

- name: Set max_pool_percent (insert)
  lineinfile:
    path: '{{ zswap_grubfile }}'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?!.*?zswap\.max_pool_percent=[0-9]+).*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 zswap.max_pool_percent={{ zswap_max_pool_percent }}"'
    backrefs: yes
  notify:
    - update-grub

- name: Set max_pool_percent (update)
  lineinfile:
    path: '{{ zswap_grubfile }}'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*?)zswap\.max_pool_percent=[0-9]+(.*?)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1zswap.max_pool_percent={{ zswap_max_pool_percent }}\2"'
    backrefs: yes
  notify:
    - update-grub

- name: Configure swap file swappiness and cache pressure
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "present"
    reload: True
  with_dict: "{{ swapfile_sysctl }}"

- name: Create swap file
  command: |
    fallocate -l {{ ((swapfile_size) | int * 1024 * 1024) }} {{ swapfile_path }}
  args:
    creates: "{{ swapfile_path }}"
  register: swapfile_register_create
  notify:
    - Initialize swap file
    - Enable swap file

- name: Set swap file permissions
  file:
    path: "{{ swapfile_path }}"
    state: "file"
    owner: "root"
    group: "root"
    mode: "0600"
  when: not ansible_check_mode

- name: Run handlers to init swap file
  meta: flush_handlers

- name: Manage swap file in /etc/fstab
  mount:
    src: "{{ swapfile_path }}"
    name: "none"
    fstype: "swap"
    opts: "sw,nofail"
    dump: "0"
    passno: "0"
    state: "present"

- name: Import configuration tasks
  import_tasks: configure.yml
  tags:
    - configure
