---
# defaults file for php

php_www_user: www-data
php_www_group: www-data

php_packages_state: present

php_required_packages:
  - "{{ php_fpm_package }}"  # exact version so that apache is not needed as dependency
  - php
  - php-gd
  - php-pgsql
  - php-xml  # installs "dom"
  - php-mbstring
  - php-curl

php_max_children: 5
php_start_servers: 2
php_min_spare_servers: 1
php_max_spare_servers: 3
