---
- name: Add analytics fetching to cron
  cron:
    name: "analytics"
    minute: "0"
    hour: "1"
    job: >-
      {{ ckan_virtual_environment }}/bin/ckan
      --config {{ ckan_ini }}
      matomo fetch
  when: ckan_matomo_analytics

- name: Check broken links cron job
  cron:
    name: "archiver"
    minute: "0"
    hour: "3"
    day: "*/3"
    job: >-
      {{ ckan_virtual_environment }}/bin/ckan
      --config {{ ckan_ini }}
      archiver update

- name: Ensure harvester cron job
  cron:
    name: "harvest"
    minute: "*/5"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} harvester run"

- name: Ensure tracking cron job
  cron:
    name: "tracking"
    minute: "0"
    hour: "22"
    job: >-
      {{ ckan_virtual_environment }}/bin/ckan
      --config {{ ckan_ini }}
      tracking update
      &&
      {{ ckan_virtual_environment }}/bin/ckan
      --config {{ ckan_ini }}
      search-index rebuild -r

- name: Ensure qa cron job
  cron:
    name: "qa"
    minute: "0"
    hour: "2"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} qa update"
  when: "'qa' in ckan_extensions"

- name: Remove qa cron job if qa not enabled
  cron:
    name: "qa"
    state: "absent"
  when: "'qa' not in ckan_extensions"

- name: Ensure report cron job
  cron:
    name: "report"
    minute: "0"
    hour: "5"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} report generate"

- name: Add email reminder about expiring datasets as a cron job
  cron:
    name: "Add email reminder"
    minute: "0"
    hour: "9"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} reminder send"

- name: Send emails about broken resource links cron job
  cron:
    name: "Send broken link email"
    minute: "0"
    hour: "10"
    day: "1"
    job: >-
      {{ ckan_virtual_environment }}/bin/ckan
      --config {{ ckan_ini }}
      archiver send_broken_link_notification

- name: Send reminder about expiring datasets as a cron job
  cron:
    name: "Send expiring reminder"
    minute: "0"
    hour: "13"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} reminder notify-expiry"

- name: Send notification about updated datasets as a cron job
  cron:
    name: "Send notification of updated datasets"
    minute: "0"
    hour: "12"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} reminder notify"


- name: Send dataset deprecation emails as a cron job
  cron:
    name: "Send deprecation emails"
    minute: "00"
    hour: "9"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} ytp-dataset update_package_deprecation"

- name: Send harvester status report emails as a cron job
  cron:
    name: "Send harvester status report emails"
    minute: "0"
    hour: "11"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config={{ ckan_ini }} opendata-harvest send-status-emails"

- name: Send stuck harvester report emails as a cron job
  cron:
    name: "Send stuck harvester report emails"
    minute: "0"
    hour: "11"
    job: "{{ ckan_virtual_environment }}/bin/ckan --config {{ ckan_ini }} opendata-harvest send-stuck-runs-report"


- name: Remove old beaker sessions from beaker_cache table
  cron:
    name: "Remove old beaker sessions"
    minute: "0"
    hour: "3"
    job: "/usr/local/sbin/beaker_session_cleanup.sh > /dev/null 2>&1"

- name: Send notification email as cron job
  cron:
    name: "Send notification email"
    minute: "0"
    hour: "8"
    job: "{{ ckan_virtual_environment }}/bin/ckan -c {{ ckan_ini }} post /api/action/send_email_notifications > /dev/null"
