drupal_domain: "{{ base_hostname }}"
drupal_secondary_domain: "{{ secondary_base_hostname }}"
drupal_initial_users: "{{ secret_ytp_users }}"
drupal_admin_email: "{{ secret_admin_email }}"
drupal_recaptcha_public_key: "{{ secret_recaptcha_public_key }}"
drupal_recaptcha_private_key: "{{ secret_recaptcha_private_key }}"
drupal_admin_username: "{{ secret_admin.username }}"
drupal_admin_password: "{{ secret_admin.password }}"
drupal_database_password: "{{ secret_database_drupal8_password }}"
drupal_hash_salt: "{{ secret_drupal_hash_salt }}"
