---
postgres_admin_user: "{{ secret_postgres_conf.admin_user }}"
postgres_admin_password: "{{ secret_postgres_conf.admin_password }}"

postgres_users:
  - username: ckan_default
    password: "{{ secret_database_ckan_password }}"
  - username: datastore_default
    password: "{{ secret_database_ckan_datastore_password }}"
  - username: drupal8
    password: "{{ secret_database_drupal8_password }}"
