---
# tasks file for opendata_frontend

- name: Ensure www path is present
  file:
    path: "/var/www"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Ensure opendata frontend server path is present
  file:
    path: "{{ opendata_frontend_server_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Ensure opendata frontend cache path is present
  file:
    path: "{{ opendata_frontend_cache_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- include_tasks: vagrant.yml
  when: opendata_frontend_deployment_environment_id == "vagrant"

- include_tasks: nonvagrant.yml
  when: opendata_frontend_deployment_environment_id != "vagrant"

