---

- name: Install required packages
  apt:
    name:
      - python-setuptools
      - python-virtualenv
    state: present


- name: Install Datapusher
  pip:
    name: "git+https://github.com/ckan/datapusher.git@master#egg=datapusher"
    virtualenv: "{{ datapusher_env }}"
    extra_args: "--exists-action=s -e"

- name: Install Datapusher requirements
  pip:
    requirements: "{{ datapusher_env }}/src/datapusher/requirements.txt"
    virtualenv: "{{ datapusher_env }}"
    virtualenv_python: "python3"
    state: present

- name: Link datapusher sources
  command: "{{ datapusher_env }}/bin/python setup.py develop"
  args:
    chdir: "{{ datapusher_env }}/src/datapusher"
  tags:
    - skip_ansible_lint

- name: Ensure Datapusher configuration file directory exists
  file:
    path: "{{ datapusher_config_directory }}"
    state: directory
    owner: "{{ datapusher_user }}"
    group: "{{ datapusher_group }}"
    mode: "0755"

- name: Import configuration tasks
  import_tasks: configure.yml
  tags:
    - configure
