---

- name: Install required packages
  apt:
    name:
      - python-setuptools
      - python-virtualenv
    state: present


- name: Install Datapusher
  pip:
    name: "git+https://github.com/6aika/datapusher.git@master#egg=datapusher"
    virtualenv: "{{ datapusher_env }}"
    extra_args: "--exists-action=s -e"

- name: Install Datapusher requirements
  pip:
    requirements: "{{ datapusher_env }}/src/datapusher/requirements.txt"
    virtualenv: "{{ datapusher_env }}"
    state: present

# TODO: Remove this when https://github.com/ckan/ckan-service-provider/pull/44
# is merged and released and released version is updated to datapusher
# requirements.txt file
- name: Override ckan-service-provider requirement
  pip:
    name: git+http://github.com/vrk-kpa/ckan-service-provider#egg=ckanserviceprovider
    virtualenv: "{{ datapusher_env }}"
    state: forcereinstall

- name: Link datapusher sources
  command: "{{ datapusher_env }}/bin/python setup.py develop"
  args:
    chdir: "{{ datapusher_env }}/src/datapusher"
  tags:
    - skip_ansible_lint

- name: Ensure Datapusher configuration file directory exists
  file:
    path: "{{ datapusher_config_directory }}"
    state: directory
    owner: "{{ datapusher_user }}"
    group: "{{ datapusher_group }}"
    mode: "0644"

- name: Import configuration tasks
  import_tasks: configure.yml
  tags:
    - configure
