---
- name: Converge
  hosts: all
  become: true
  vars:
    apache_sites:
      - name: datapusher
        config: |
          <VirtualHost *:8800>

              ServerName ckan

              # this is our app
              WSGIScriptAlias / /etc/ckan/default/datapusher.wsgi

              # pass authorization info on (needed for rest api)
              WSGIPassAuthorization On

              # Deploy as a daemon (avoids conflicts between CKAN instances)
              WSGIDaemonProcess datapusher display-name=datapusher processes=1 threads=15

              WSGIProcessGroup datapusher

              ErrorLog /var/log/apache2/datapusher.error.log
              CustomLog /var/log/apache2/datapusher.custom.log combined

              <Directory "/" >
                  Require all granted
              </Directory>

          </VirtualHost>
    apache_port_config: |
      NameVirtualHost *:{{ apache_port }}
      Listen {{ apache_port }}

      NameVirtualHost *:8800
      Listen 8800

      {% if apache_testing_ports is defined %}
        {% for port in apache_testing_ports %}
          Listen {{ port }}
        {% endfor %}
      {% endif %}
    apache_port: 80
    datapusher_env: /usr/lib/ckan/datapusher
    datapusher_group: www-data
    datapusher_user: www-data
    datapusher_deployment_environment_id: molecule
  roles:
    - role: datapusher
