---

- name: Set PHP pathinfo
  ini_file:
    dest: "{{ php_fpm_ini_file }}"
    section: PHP
    option: cgi.fix_pathinfo
    value: "0"
    mode: "0644"
  notify: restart php-fpm service

- name: Set PHP upload_max_filesize
  ini_file:
    dest: "{{ php_fpm_ini_file }}"
    section: PHP
    option: upload_max_filesize
    value: "10M"
    mode: "0644"
  notify: restart php-fpm service

- name: Set PHP session samesite flag
  ini_file:
    dest: "{{ php_fpm_ini_file }}"
    section: Session
    option: session.cookie_samesite
    value: "Lax"
    mode: "0644"
  notify: restart php-fpm service

- name: Set socket to listen
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen
    value: /tmp/phpfpm.socket
    mode: "0644"
  notify: restart php-fpm service

- name: Set socket listen owner
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen.owner
    value: "{{ php_www_user }}"
    mode: "0644"
  notify: restart php-fpm service

- name: Set socket listen group
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen.group
    value: "{{ php_www_group }}"
    mode: "0644"
  notify: restart php-fpm service

- name: Set socket listen mode
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen.mode
    value: "0660"
    mode: "0644"
  notify: restart php-fpm service

- name: Configure pm.max_children setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.max_children
    value: "{{ php_max_children }}"
    mode: "0644"
  notify: restart php-fpm service

- name: Configure pm.start_servers setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.start_servers
    value: "{{ php_start_servers }}"
    mode: "0644"
  notify: restart php-fpm service

- name: Configure pm.max_spare_servers setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.max_spare_servers
    value: "{{ php_max_spare_servers }}"
    mode: "0644"
  notify: restart php-fpm service

- name: Configure pm.min_spare_servers setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.min_spare_servers
    value: "{{ php_min_spare_servers }}"
    mode: "0644"
  notify: restart php-fpm service
