---
# tasks file for php

- name: Get distribution based variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: always

- name: Add repository for up to date php
  apt_repository:
    repo: ppa:ondrej/php


- name: Get PHP and required extensions
  package:
    name: "{{ php_required_packages }}"
    state: "{{ php_packages_state }}"

- name: Socket setup
  import_tasks: configure-fpm.yml
  tags:
    - configure

- name: Start and enable php-fpm service
  systemd:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: true
