---
ckan_profiling_enabled: true
ckan_smtp_use_tls: False
ckan_smtp_port: 1025
ckan_site_protocol: "http"
ckan_disqus_name: "{{ disqus_name }}"
ckan_enable_cloudstorage: false
ckan_postgres_installed_locally: true
ckan_debug_enabled: true
ckan_deployment_environment_id: 'vagrant'

ckan_testing_ports:
  - 9090

ckan_config_files:
  - template: ckan.ini.j2
    file: "{{ ckan_ini }}"
    db_server: "{{ ckan_postgres.server.host }}"
    db_ckan_username: "{{ ckan_postgres.users.ckan.username }}"
    db_ckan_password: "{{ ckan_postgres.users.ckan.password }}"
    db_ckan_database: "{{ ckan_postgres.databases.ckan.name }}"
    db_ckan_datastore_password: "{{ ckan_postgres.users.ckan_datastore.password }}"
    db_ckan_datastore_username: "{{ ckan_postgres.users.ckan_datastore.username }}"
    db_ckan_datastore_database: "{{ ckan_postgres.databases.ckan_datastore.name }}"
    solr_path: "{{ ckan_solr_path }}"
    hostname: "{{ ckan_hostname }}"
    redis_db: "{{ ckan_redis_db }}"
    debug_enabled: "{{ ckan_debug_enabled }}"
  - template: ckan.ini.j2
    file: /etc/ckan/default/test.ini
    db_server: "{{ ckan_postgres.server.host }}"
    db_ckan_username: ckan_test
    db_ckan_password: pass
    db_ckan_database: ckan_test
    db_ckan_datastore_username: datastore_test
    db_ckan_datastore_password: pass
    db_ckan_datastore_database: datastore_test
    solr_path: "solr/ckan_test"
    hostname: "vagrant.avoindata.fi:9000"
    redis_db: "1"
    debug_enabled: false

wsgi_config_files:
  - template: ckan-uwsgi.ini.j2
    file: "{{ ckan_uwsgi_conf }}"
    ckan_wsgi_script: "{{ ckan_wsgi_script }}"
  - template: wsgi.py.j2
    file: "{{ ckan_wsgi_script }}"

ckan_log_files:
  - "{{ ckan_log_path }}/ckan.log"
  - "{{ ckan_log_path }}/ckan_test.log"

ckan_sentry_integration_enabled: false
ckan_notifications_to_maintainers_enabled: true

ckan_matomo_analytics: "{{ matomo_analytics }}"
