---
# defaults file for solr
solr_port: "8983"
solr_host: localhost
solr_cores: []

solr_version: 6.5.1
solr_download_url: http://archive.apache.org/dist/lucene/solr/{{solr_version }}/solr-{{ solr_version }}.tgz

solr_user: solr
solr_group: solr
solr_home: /var/solr
solr_requirements:
  - openjdk-8-jre

solr_install_path: /opt/solr-{{ solr_version }}
solr_config_file: /etc/default/solr.in.sh

solr_service_name: solr
solr_service_state: started
solr_service_enabled: true

solr_core_config_files:
  - schema.xml
  - solrconfig.xml
