---
- name: Converge
  hosts: all
  become: true

  vars:
    opendata_frontend_modules_path: "../../../../modules"
    drupal_modules_path: "../../../../modules"
    hostname: vagrant.avoindata.fi
    drupal_configure_instance: true
    drupal_database_name: drupal8
    drupal_database_username: drupal8
    drupal_database_password: pass
    drupal_admin_username: admin
    drupal_admin_password: administrator
    drupal_site_name: avoindata.fi
    drupal_fqdn: 'vagrant.avoindata.fi'
    drupal_domain: ''
    drupal_secondary_fqdn: '127.0.0.1'
    drupal_secondary_domain: ''
    drupal_smtp_server_domain: localhost
    drupal_smtp_username: username
    drupal_smtp_password: password
    drupal_email_from: no-reply@localhost
    drupal_disqus_name: "localhost-avoindata-fi"
    drupal_hash_salt: IzqME5cJk_x1ZV7oO3UXtHnM7p8R-mLVU5ZiKPWbzDQ
    drupal_editor_rolename: editor
    drupal_publisher_rolename: publisher
    drupal_ckan_admin_rolename: ckan_admin
    drupal_roles:
      - { 'username': "{{ drupal_admin_username }}", 'role': "{{ drupal_ckan_admin_rolename }}" }
      - { 'username': "test-editor", 'role': "{{ drupal_editor_rolename }}" }
      - { 'username': "test-editor", 'role': "{{ drupal_ckan_admin_rolename }}" }
      - { 'username': "test-publisher", 'role': "{{ drupal_publisher_rolename }}" }
    drupal_initial_users:
      - username: 'test-editor'
        password: 'test-editor'
        email: 'editor@localhost'
      - username: 'test-publisher'
        password: 'test-publisher'
        email: 'publisher@localhost'
      - username: 'test-user'
        password: 'test-user'
        email: 'user@localhost'
    postgres_global_config:
      - option: listen_addresses
        value: "*"
      - option: port
        value: "5432"
      - option: max_connections
        value: "100"
      - option: unix_socket_directories
        value: '/var/run/postgresql'
      - option: ssl
        value: "true"
      - option: shared_buffers
        value: "24MB"
      - option: "log_line_prefix"
        value: '%t '
      - option: datestyle
        value: 'iso, mdy'
      - option: lc_messages
        value: 'en_US.utf8'
      - option: lc_monetary
        value: 'en_US.utf8'
      - option: lc_numeric
        value: 'en_US.utf8'
      - option: lc_time
        value: 'en_US.utf8'
      - option: default_text_search_config
        value: 'pg_catalog.english'
    postgres_users:
      - username: drupal8
        password: pass
    postgres_databases:
      - name: drupal8
        owner: drupal8
    nginx_fqdn: "127.0.0.1"
    nginx_domain: ''
    nginx_secondary_fqdn: "localhost"
    nginx_secondary_domain: ''

    nginx_sites:
      - template: 'nginx_site_config.j2'
        destination: 'sites-available/ytp'
        server_name: "{{ nginx_fqdn }}"
        snippet: 'ytp.conf'
        base_hostname: "{{ nginx_domain }}"
        port: "{{ nginx_port }}"
      - template: 'nginx_site_config.j2'
        destination: 'sites-available/ytp-secondary'
        server_name: "{{ nginx_secondary_fqdn }}"
        snippet: 'ytp-secondary.conf'
        base_hostname: "{{ nginx_secondary_domain }}"
        port: "{{ nginx_port }}"

    nginx_enabled_sites:
      - "ytp"
      - "ytp-secondary"

    nginx_hostname_language: "fi"
    nginx_secondary_hostname_language: "en"

    nginx_snippet_files:
      - template: 'server.config.j2'
        destination: 'ytp.conf'
        root_redirect: "{{ nginx_hostname_language }}"
        ckan_port: "{{ nginx_ckan_port }}"
      - template: 'server.config.j2'
        destination: 'ytp-secondary.conf'
        root_redirect: "{{ nginx_secondary_hostname_language }}"
        ckan_port: "{{ nginx_ckan_port }}"
      - template: 'nginx_security_headers.conf.j2'
        destination: 'nginx_security_headers.conf'

    nginx_max_resource_size: "5000"

    nginx_root_path: "/srv/ytp"

    nginx_ckan_port: "8080"
    apache_service_state: stopped
    apache_service_enabled: false

  roles:
    - role: drupal
