---
- name: Copy base Nginx configuration
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"
    owner: root
    group: root
  notify: Restart Nginx

- name: Copy fastcgi_params configuration file
  template:
    src: "fastcgi_params.j2"
    dest: "/etc/nginx/fastcgi_params"
    mode: "0644"
    owner: root
    group: root
  notify: Restart Nginx

- name: Copy Nginx sites
  template:
    src: "{{ item.template }}"
    dest: "/etc/nginx/{{ item.destination }}"
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ nginx_sites }}"
  notify: Restart Nginx
  tags:
    - nginx

- name: Copy snippets files
  template:
    src: "{{ item.template }}"
    dest: "/etc/nginx/snippets/{{ item.destination }}"
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ nginx_snippet_files }}"
  notify: Restart Nginx
  tags:
    - nginx

- name: Disable Nginx sites
  file:
    path: "/etc/nginx/sites-enabled/{{ item }}"
    state: absent
  with_items: "{{ nginx_disabled_sites }}"
  notify: Restart Nginx

- name: Enable Nginx site
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items: "{{ nginx_enabled_sites }}"
  tags:
    - nginx
  notify: Restart Nginx

- name: Ensure Nginx service state
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: true


# Fetch full catalogs on web servers
- name: Copy fetch script
  copy:
    src: fetch_catalogs.bash
    dest: /var/www/fetch_catalogs.bash
    mode: "0700"
  tags:
    - nginx

- name: Ensure cron for fetch catalog
  cron:
    name: "Fetch catalogs"
    hour: "0"
    job: "bash /var/www/fetch_catalogs.bash"
  tags:
    - nginx
