---

# THESE VARS ARE PUBLIC, DO NOT PUT SECRETS HERE

hostname: infratest.betaavoindata.fi
hostname_language: fi
secondary_hostname: infratest.betaopendata.fi
secondary_hostname_language: en
base_hostname: "betaavoindata.fi"
secondary_base_hostname: "betaopendata.fi"
smtp_server_domain: "email-smtp.eu-west-1.amazonaws.com"
smtp_user: "{{ secret_smtp_user }}"
smtp_password: "{{ secret_smtp_password }}"

deployment_environment_id: infratest
disqus_name: ""
ansible_python_interpreter: "{{ ansible_playbook_python }}"
aws_profile: opendata

rds_domain_common_part: cpvtsnlvlcqp.eu-west-1.rds.amazonaws.com
postgres_host: avoindata-{{ deployment_environment_id }}.{{ rds_domain_common_part }}

AWS:
  enabled: true
  region: S3_EU_WEST
  use_iam_role: true
  ckan_s3_bucket: avoindata-infratest-datasets
  smtp_server_domain: ""
