---

# Note! Setting environment variable
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# before running the playbook is necessary on macOS High Sierra and later

- name: This playbook configures opendata web stack using AWS cloudformation
  hosts: "localhost"
  connection: "local"
  gather_facts: no
  # environment:
  #   AWS_PROFILE: "{{ aws_profile }}"

  tasks:
  - name: Configure web stack
    cloudformation:
      stack_name: "{{ deployment_environment_id }}-web"
      state: present
      region: "{{ lookup('aws_ssm', '/{{ deployment_environment_id }}/web/region') }}"
      create_changeset: true
      template: ../cloudformation/instances.yml
      template_parameters:
        DatabaseSecurityGroup: "/{{ deployment_environment_id }}/web/database_security_group"
        EFSFileSystem: "/{{ deployment_environment_id }}/web/efs_file_system"
        EFSSecurityGroup: "/{{ deployment_environment_id }}/web/efs_security_group"
        EnvironmentName: "/{{ deployment_environment_id }}/web/environment_name"
        HostedZoneId: "/{{ deployment_environment_id }}/web/hosted_zone_id"
        HostedZoneIdAlternate: "/{{ deployment_environment_id }}/web/hosted_zone_id_alternate"
        NumberOfSubnets: "/{{ deployment_environment_id }}/web/number_of_subnets"
        PrivateALBSubnets: "/{{ deployment_environment_id }}/web/private_subnets"
        PublicALBCertificate: "/{{ deployment_environment_id }}/web/public_alb_certificate"
        PublicALBSubnets: "/{{ deployment_environment_id }}/web/public_alb_subnets"
        RedisMaintenanceWindow: "/{{ deployment_environment_id }}/redis/maintenance_window"
        RedisNodeType: "/{{ deployment_environment_id }}/redis/node_type"
        RedisVersion: "/{{ deployment_environment_id }}/redis/version"
        Vpc: "/{{ deployment_environment_id }}/web/vpc"
        WafAllTrafficRequestSampling: "/{{ deployment_environment_id }}/web/waf-request-sampling-all-traffic"
        WafAllowedIpsRequestSampling: "/{{ deployment_environment_id }}/web/waf-request-sampling-allowed-ips"
        WafBannedIpsRequestSampling: "/{{ deployment_environment_id }}/web/waf-request-sampling-banned-ips"
        WafHighPriorityCountryCodes: "/{{ deployment_environment_id }}/web/waf-high-priority-country-codes"
        WafHighPriorityRateLimit: "/{{ deployment_environment_id }}/web/waf-rate-limit-high-priority"
        WafHighPriorityRequestSampling: "/{{ deployment_environment_id }}/web/waf-request-sampling-high-priority"
        WafRateLimit: "/{{ deployment_environment_id }}/web/waf-rate-limit"
        WafRequestSampling: "/{{ deployment_environment_id }}/web/waf-request-sampling"
        BannedIPs: "/{{ deployment_environment_id }}/web/banned-ips"
        AllowedIPs: "/{{ deployment_environment_id }}/web/allowed-ips"
        LogEnabled: "/{{ deployment_environment_id }}/web/log_enabled"
        LogExpirationDays: "/{{ deployment_environment_id }}/web/log_expiration_days"