---
# tasks file for solr

- name: Install Solr requirements
  apt:
    name: "{{ solr_requirements }}"
    state: present

- name: Check Solr installation status
  stat:
    path: "{{ solr_install_path }}"
  register: solr_install_path_status

- name: Download Solr package
  get_url:
    url: "{{ solr_download_url }}"
    dest: /tmp
  register: solr_download_status
  when: solr_install_path_status.stat.isdir is not defined

- name: Extract Solr installer from the archive
  unarchive:
    src: "/tmp/solr-{{ solr_version }}.tgz"
    dest: /tmp/
    extra_opts:
      - solr-{{ solr_version }}/bin/install_solr_service.sh
      - --strip-components=2
    creates: "/tmp/install_solr_service.sh"
    remote_src: true
  when: solr_download_status.changed
  tags:
    - skip_ansible_lint

- name: Install solr using installer
  command: /tmp/install_solr_service.sh  /tmp/solr-{{ solr_version }}.tgz -d /var/solr -u {{ solr_user }} -s solr -p 8983 -f
  when: solr_download_status.changed
  tags:
    - skip_ansible_lint

- name: Ensure solr is state is desired
  service:
    name: "{{ solr_service_name }}"
    state: "{{ solr_service_state }}"
    enabled: "{{ solr_service_enabled }}"

- import_tasks: configure.yml
  tags: configure
