---
nginx_fqdn: "{{ hostname }}"
nginx_domain: ""
nginx_secondary_fqdn: "{{ secondary_hostname }}"
nginx_secondary_domain: ""

nginx_sites:
  - template: 'nginx_site_config.j2'
    destination: 'sites-available/ytp'
    server_name: "{{ nginx_fqdn }}"
    snippet: 'ytp.conf'
    base_hostname: "{{ nginx_domain }}"
    port: "{{ nginx_port }}"
  - template: 'nginx_site_config.j2'
    destination: 'sites-available/ytp-secondary'
    server_name: "{{ nginx_secondary_fqdn }}"
    snippet: 'ytp-secondary.conf'
    base_hostname: "{{ nginx_secondary_domain }}"
    port: "{{ nginx_port }}"

nginx_enabled_sites:
  - "ytp"
  - "ytp-secondary"

nginx_hostname_language: "fi"
nginx_secondary_hostname_language: "en"

nginx_snippet_files:
  - template: 'server.config.j2'
    destination: 'ytp.conf'
    root_redirect: "{{ nginx_hostname_language }}"
    ckan_port: "{{ nginx_ckan_port }}"
  - template: 'server.config.j2'
    destination: 'ytp-secondary.conf'
    root_redirect: "{{ nginx_secondary_hostname_language }}"
    ckan_port: "{{ nginx_ckan_port }}"
  - template: 'nginx_security_headers.conf.j2'
    destination: 'nginx_security_headers.conf'

nginx_max_resource_size: "{{ ckan_max_resource_size }}"

nginx_root_path: "/srv/ytp"

nginx_ckan_port: "{{ ckan_port }}"
