---
# tasks file for composer

- name: Set php_executable variable to a default if not defined.
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Check if Composer is installed.
  stat:
    path: "{{ composer_path }}"
  register: composer_bin

- name: Install Composer
  script: install_composer.sh
  when: not composer_bin.stat.exists

- name: Move Composer globally
  command: mv composer.phar "{{ composer_path }}"
  args:
    creates: "{{ composer_path }}"

- name: Set Composer permissions
  file:
    path: "{{ composer_path }}"
    mode: "a+x"

- name: Ensure composer directory exists
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
    mode: "0644"
    state: directory

- name: Install dependencies for dependency management
  composer:
    command: require
    global_command: true
    arguments: alchemy/zippy:0.4.3
