---
- name: Converge
  hosts: all
  become: true
  vars:
    opendata_frontend_modules_path: "../../../../modules"
    drupal_modules_path: "../../../../modules"
    hostname: vagrant.avoindata.fi
    hostname_language: fi
    secondary_hostname: vagrant.opendata.fi
    secondary_hostname_language: en
    drupal_configure_instance: true
    drupal_database_name: drupal8
    drupal_database_username: drupal8
    drupal_database_password: pass
    drupal_admin_username: admin
    drupal_admin_password: administrator
    drupal_site_name: avoindata.fi
    drupal_fqdn: '{{ hostname }}'
    drupal_domain: ''
    drupal_secondary_fqdn: '127.0.0.1'
    drupal_secondary_domain: ''
    drupal_smtp_server_domain: localhost
    drupal_smtp_username: username
    drupal_smtp_password: password
    drupal_email_from: no-reply@localhost
    drupal_disqus_name: "localhost-avoindata-fi"
    drupal_hash_salt: IzqME5cJk_x1ZV7oO3UXtHnM7p8R-mLVU5ZiKPWbzDQ
    drupal_editor_rolename: editor
    drupal_publisher_rolename: publisher
    drupal_ckan_admin_rolename: ckan_admin
    drupal_roles:
      - { 'username': "{{ drupal_admin_username }}", 'role': "{{ drupal_ckan_admin_rolename }}" }
      - { 'username': "test-editor", 'role': "{{ drupal_editor_rolename }}" }
      - { 'username': "test-editor", 'role': "{{ drupal_ckan_admin_rolename }}" }
      - { 'username': "test-publisher", 'role': "{{ drupal_publisher_rolename }}" }
    drupal_initial_users:
      - username: 'test-editor'
        password: 'test-editor'
        email: 'editor@localhost'
      - username: 'test-publisher'
        password: 'test-publisher'
        email: 'publisher@localhost'
      - username: 'test-user'
        password: 'test-user'
        email: 'user@localhost'
    postgres_global_config:
      - option: listen_addresses
        value: "*"
      - option: port
        value: "5432"
      - option: max_connections
        value: "100"
      - option: unix_socket_directories
        value: '/var/run/postgresql'
      - option: ssl
        value: "true"
      - option: shared_buffers
        value: "24MB"
      - option: "log_line_prefix"
        value: '%t '
      - option: datestyle
        value: 'iso, mdy'
      - option: lc_messages
        value: 'en_US.utf8'
      - option: lc_monetary
        value: 'en_US.utf8'
      - option: lc_numeric
        value: 'en_US.utf8'
      - option: lc_time
        value: 'en_US.utf8'
      - option: default_text_search_config
        value: 'pg_catalog.english'
    postgres_users:
      - username: ckan_default
        password: pass
      - username: datastore_default
        password: pass
      - username: drupal8
        password: pass

    postgres_databases:
      - name: ckan_default  # ckan
        owner: ckan_default
      - name: datastore_default  # ckan_datastore
        owner: ckan_default
      - name: drupal8
        owner: drupal8

    postgres_spatial_databases:
      - name: ckan_default
        owner: ckan_default
    cache_path: "{{ server_path }}/cache"
    # for nginx
    basic_auth_path: false
    base_hostname: ""
    secondary_base_hostname: ""
    nginx_port: 80
    ckan_port: 8080
    log_path: /var/log/ckan
    ckan_extensions_path: "../../../../../modules"
    ckan_deployment_environment_id: 'molecule'

  roles:
    - role: ckan
